# lib.sh 
#read from state file. default to 0 if missing or broken
read_index() {
    local file="$1"
    local idx
    read -r idx < "$file" 2>/dev/null || idx=0
    #ensure it's actually a number
    [[ "$idx" =~ ^[0-9]+$ ]] || idx=0
    echo "$idx"
}

#advance an index file by 1, wrapping at (length of list)
advance_index() {
    local file="$1"
    local len="$2"
    local idx
    idx=$(read_index "$file")
    idx=$(( (idx + 1) % len ))
    echo "$idx" > "$file"
    echo "$idx"
}

#Color CSS generation
#write colors.css and accent.color
apply_color() {
    local hex="$1"

    # Write accent.color — single hex, consumed by hyprland.conf / any other configs
    echo "$hex" > "$ACCENT_FILE"
    
    #convert to rgb format (possible use fo rgb() in css or any other config format)
    local r g b
    r=$(( 16#${hex:1:2} ))
    g=$(( 16#${hex:3:2} ))
    b=$(( 16#${hex:5:2} ))

    #generate colors.css (if any later config needs it)
    cat > "$COLORS_CSS" <<EOF
/* Auto-generated by themectl — do not edit manually */
:root {
    --accent:       ${hex};
    --accent-rgb:   ${r}, ${g}, ${b};
    --accent-alpha: rgba(${r}, ${g}, ${b}, 0.85);
}
EOF

}

apply_wallpaper() {
    local wallpaper_path="$1"
    echo "$(basename "$wallpaper_path")" > "${STATE_DIR}/current_wallpaper_name"
}

accent_from_wallpaper() {
    [[ -z "$1" ]] && echo "Usage: accent <image>" && return 1
    accent_hex_from_wallpaper=$(magick "$1" \
        -resize 50x50! \
        -colorspace HSL \
        txt:- 2>/dev/null | \
    awk '
        NR > 1 {
            if (match($0, /hsla?\(([0-9.]+),([0-9.]+)%,([0-9.]+)%/, a)) {
                h = a[1]; s = a[2]; l = a[3]
                score = s * (1 - (2*l/100 - 1)^2)
                if (score > best) {
                    best = score
                    bh = h; bs = s; bl = l
                }
            }
        }
        END {
            h = bh/360; s = bs/100; l = bl/100
            if (s > 1) s = 1
            if (l > 1) l = 1
            if (s == 0) { r = g = b = l }
            else {
                q = l < 0.5 ? l*(1+s) : l+s-l*s
                p = 2*l - q
                r = hue2rgb(p, q, h + 1/3)
                g = hue2rgb(p, q, h)
                b = hue2rgb(p, q, h - 1/3)
            }
            r = r < 0 ? 0 : (r > 1 ? 1 : r)
            g = g < 0 ? 0 : (g > 1 ? 1 : g)
            b = b < 0 ? 0 : (b > 1 ? 1 : b)
            printf "#%02x%02x%02x", int(r*255), int(g*255), int(b*255)
        }
        function hue2rgb(p, q, t) {
            if (t < 0) t += 1
            if (t > 1) t -= 1
            if (t < 1/6) return p + (q-p)*6*t
            if (t < 1/2) return q
            if (t < 2/3) return p + (q-p)*(2/3-t)*6
            return p
        }
    ')
}
