# lib.sh 
#read from state file. default to 0 if missing or broken
read_index() {
    local file="$1"
    local idx
    read -r idx < "$file" 2>/dev/null || idx=0
    #ensure it's actually a number
    [[ "$idx" =~ ^[0-9]+$ ]] || idx=0
    echo "$idx"
}

#advance an index file by 1, wrapping at (length of list)
advance_index() {
    local file="$1"
    local len="$2"
    local idx
    idx=$(read_index "$file")
    idx=$(( (idx + 1) % len ))
    echo "$idx" > "$file"
    echo "$idx"
}

#Color CSS generation
#write colors.css and accent.color
apply_color() {
    local hex="$1"

    # Write accent.color — single hex, consumed by hyprland.conf / any other configs
    echo "$hex" > "$ACCENT_FILE"

    #convert to rgb format (possible use fo rgb() in css or any other config format)
    local r g b
    r=$(( 16#${hex:1:2} ))
    g=$(( 16#${hex:3:2} ))
    b=$(( 16#${hex:5:2} ))

    #generate colors.css (if any later config needs it)
    cat > "$COLORS_CSS" <<EOF
/* Auto-generated by themectl — do not edit manually */
:root {
    --accent:        ${hex};
    --accent-rgb:    ${r}, ${g}, ${b};
    --accent-alpha:  rgba(${r}, ${g}, ${b}, 0.85);
}
EOF

    source "$THEMES_DIR/update_theme.sh"
}

apply_wallpaper() {
    local wallpaper_path="$1"
    echo "$(basename "$wallpaper_path")" > "${STATE_DIR}/current_wallpaper_name"
    source "$THEMES_DIR/update_theme.sh"
}
